version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hh_db"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/hh_db
      - SECRET_KEY=secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "5173:5173"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
