version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./Backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/hh_db
      - SECRET_KEY=secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "5173:5173"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
